FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-authkit[postgresql,redis] \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

COPY dagster.yaml /opt/dagster/dagster_home/dagster.yaml
COPY workspace.yaml /opt/dagster/dagster_home/workspace.yaml

ENV DAGSTER_HOME=/opt/dagster/dagster_home

WORKDIR /opt/dagster/dagster_home
