FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-postgres \
    dagster-docker

COPY user_code/ /opt/dagster/app/
COPY dagster.yaml /opt/dagster/dagster_home/dagster.yaml

ENV DAGSTER_HOME=/opt/dagster/dagster_home

WORKDIR /opt/dagster/app

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "defs"]
