name: Security Audit

on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [main]
    paths:
      - pyproject.toml
      - uv.lock
      - .github/workflows/*.yml
  pull_request:
    branches: [main]
    paths:
      - pyproject.toml
      - uv.lock
      - .github/workflows/*.yml
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        id: sarif
        with:
          advanced-security: false

  pip-audit:
    name: pip-audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2

      - name: Run pip-audit
        run: uv tool run pip-audit --strict --desc
